//! Integration tests for BM25 full-text search (P1.3): `build_fts5_query`,
//! `Qmd::search_lex`, `extract_snippet`, context propagation and the
//! upstream golden fixture.
//!
//! Ported upstream coverage: `test/store.test.ts` FTS query/search cases
//! and `test/store-cjk-fts.test.ts`; plus the `lex_golden.json` fixture
//! generated by `scripts/gen_lex_golden.ts` against upstream v2.8.3.

#![allow(
    unused_crate_dependencies,
    reason = "each test binary only uses a subset of the package deps"
)]
#![allow(
    clippy::tests_outside_test_module,
    clippy::shadow_unrelated,
    clippy::field_reassign_with_default,
    clippy::float_cmp,
    clippy::doc_markdown,
    clippy::indexing_slicing,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::missing_assert_message,
    clippy::panic,
    reason = "idiomatic test-code patterns"
)]

use std::fs;
use std::path::Path;

use qmd::{CollectionSpec, Environment, LexOptions, Qmd, SearchSource};

fn write(dir: &Path, rel: &str, content: &str) {
    let path = dir.join(rel);
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, content).unwrap();
}

fn open_with_docs(docs: &Path, db: &Path) -> Qmd {
    let qmd = Qmd::builder(db)
        .environment(Environment::default())
        .build()
        .unwrap();
    qmd.add_collection(
        "docs",
        &CollectionSpec {
            path: docs.to_string_lossy().into_owned(),
            ..CollectionSpec::default()
        },
    )
    .unwrap();
    qmd
}

fn indexed_fixture_db(tmp: &Path) -> (Qmd, serde_json::Value) {
    let fixture: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/lex_golden.json")).unwrap();
    let docs = tmp.join("docs");
    for doc in fixture["documents"].as_array().unwrap() {
        write(
            &docs,
            doc["path"].as_str().unwrap(),
            doc["body"].as_str().unwrap(),
        );
    }
    let qmd = open_with_docs(&docs, &tmp.join("i.sqlite"));
    qmd.update(&qmd::UpdateOptions::default(), &mut |_| {})
        .unwrap();
    (qmd, fixture)
}

fn lex(qmd: &Qmd, query: &str, limit: usize) -> Vec<qmd::SearchResult> {
    qmd.search_lex(
        query,
        &LexOptions {
            limit: Some(limit),
            collections: None,
        },
    )
    .unwrap()
}

// --- buildFTS5Query (upstream store.ts:3946-4055) --------------------------

#[test]
fn build_fts5_query_cases() {
    // Cases from the upstream doc comment.
    assert_eq!(
        qmd::build_fts5_query("performance -sports"),
        Some("\"performance\"* NOT \"sports\"*".to_owned())
    );
    assert_eq!(
        qmd::build_fts5_query("\"machine learning\""),
        Some("\"machine learning\"".to_owned())
    );
    assert_eq!(
        qmd::build_fts5_query("multi-agent memory"),
        Some("\"multi agent\" AND \"memory\"*".to_owned())
    );
    assert_eq!(
        qmd::build_fts5_query("DEC-0054"),
        Some("\"dec 0054\"".to_owned())
    );
    assert_eq!(
        qmd::build_fts5_query("-multi-agent"),
        None // negation alone cannot match
    );
    assert_eq!(
        qmd::build_fts5_query("\"DEC-0054\""),
        Some("\"dec 0054\"".to_owned())
    );
    assert_eq!(
        qmd::build_fts5_query("src/lib/i18n.ts"),
        Some("\"src lib i18n ts\"".to_owned())
    );
    assert_eq!(
        qmd::build_fts5_query("2026.4.10"),
        Some("\"2026 4 10\"".to_owned())
    );
    assert_eq!(
        qmd::build_fts5_query("hello"),
        Some("\"hello\"*".to_owned())
    );
    assert_eq!(qmd::build_fts5_query("!!!"), None);
    assert_eq!(qmd::build_fts5_query(""), None);
    assert_eq!(qmd::build_fts5_query("   "), None);
}

#[test]
fn build_fts5_query_cjk_becomes_char_phrase() {
    assert_eq!(
        qmd::build_fts5_query("数据库"),
        Some("\"数 据 库\"".to_owned())
    );
    // Mixed CJK and Latin
    assert_eq!(
        qmd::build_fts5_query("データ rust"),
        Some("\"デ ー タ\" AND \"rust\"*".to_owned())
    );
}

#[test]
fn validate_lex_query_checks() {
    assert!(qmd::validate_lex_query("hello").is_none());
    assert!(qmd::validate_lex_query("a\nb").is_some());
    assert!(qmd::validate_lex_query("\"unclosed").is_some());
    assert!(qmd::validate_lex_query("\"ok\"").is_none());
}

#[test]
fn validate_semantic_query_checks() {
    assert!(qmd::validate_semantic_query("hello").is_none());
    assert!(qmd::validate_semantic_query("-term").is_some());
    assert!(qmd::validate_semantic_query("hello -term").is_some());
    // Hyphenated compounds must not be seen as negation.
    assert!(qmd::validate_semantic_query("multi-agent").is_none());
    assert!(qmd::validate_semantic_query("real-time write-ahead").is_none());
}

// --- searchFTS --------------------------------------------------------------

#[test]
fn search_lex_matches_golden_fixture() {
    let tmp = tempfile::tempdir().unwrap();
    let (qmd, fixture) = indexed_fixture_db(tmp.path());

    for q in fixture["queries"].as_array().unwrap() {
        let query = q["query"].as_str().unwrap();
        let limit = usize::try_from(q["limit"].as_u64().unwrap()).unwrap();
        let collections = q["collection"].as_str().map(|c| vec![c.to_owned()]);
        let results = qmd
            .search_lex(
                query,
                &LexOptions {
                    limit: Some(limit),
                    collections,
                },
            )
            .unwrap();

        let expected = q["results"].as_array().unwrap();
        let got: Vec<&str> = results.iter().map(|r| r.filepath.as_str()).collect();
        let want: Vec<&str> = expected
            .iter()
            .map(|r| r["filepath"].as_str().unwrap())
            .collect();
        assert_eq!(got, want, "rank order differs for {query:?}");

        for (r, e) in results.iter().zip(expected.iter()) {
            let want_score = e["score"].as_f64().unwrap();
            assert!(
                (r.score - want_score).abs() < 1e-9,
                "score differs for {query:?} {}: got {}, want {}",
                r.filepath,
                r.score,
                want_score
            );
        }
        // Upstream validation outcome agrees too.
        let want_err = q["lex_validation"].as_str();
        assert_eq!(qmd::validate_lex_query(query).is_some(), want_err.is_some());
    }
}

#[test]
fn eval_bm25_golden_matches_upstream() {
    // AC3: upstream `test/eval-docs` corpus (vendored in
    // `fixtures/eval-docs/`) + the 24 queries from `eval-bm25.test.ts`,
    // replayed through `search_lex`. Regenerate with
    // `QMD_UPSTREAM=… bun scripts/gen_eval_golden.ts`.
    let fixture: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/eval_bm25_golden.json")).unwrap();
    let tmp = tempfile::tempdir().unwrap();
    let docs = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/eval-docs");
    let qmd = Qmd::builder(tmp.path().join("i.sqlite"))
        .environment(Environment::default())
        .build()
        .unwrap();
    qmd.add_collection(
        "eval-docs",
        &CollectionSpec {
            path: docs.to_string_lossy().into_owned(),
            ..CollectionSpec::default()
        },
    )
    .unwrap();
    qmd.update(&qmd::UpdateOptions::default(), &mut |_| {})
        .unwrap();

    for q in fixture["queries"].as_array().unwrap() {
        let query = q["query"].as_str().unwrap();
        let results = qmd
            .search_lex(
                query,
                &LexOptions {
                    limit: Some(5),
                    collections: None,
                },
            )
            .unwrap();
        let expected = q["results"].as_array().unwrap();
        let got: Vec<&str> = results.iter().map(|r| r.filepath.as_str()).collect();
        let want: Vec<&str> = expected
            .iter()
            .map(|r| r["filepath"].as_str().unwrap())
            .collect();
        assert_eq!(got, want, "rank order differs for {query:?}");
        for (r, e) in results.iter().zip(expected.iter()) {
            let want_score = e["score"].as_f64().unwrap();
            assert!(
                (r.score - want_score).abs() < 1e-9,
                "score differs for {query:?} {}: got {}, want {}",
                r.filepath,
                r.score,
                want_score
            );
        }
    }
}

#[test]
fn search_lex_result_fields() {
    let tmp = tempfile::tempdir().unwrap();
    let docs = tmp.path().join("docs");
    write(&docs, "hello.md", "# Hello World\n\nhello world\n");
    let qmd = open_with_docs(&docs, &tmp.path().join("i.sqlite"));
    qmd.update(&qmd::UpdateOptions::default(), &mut |_| {})
        .unwrap();

    let [r] = lex(&qmd, "hello", 20).try_into().unwrap();
    assert_eq!(r.filepath, "qmd://docs/hello.md");
    assert_eq!(r.display_path, "docs/hello.md");
    assert_eq!(r.title, "Hello World");
    assert_eq!(r.collection_name, "docs");
    assert_eq!(r.docid.len(), 6);
    assert!(r.hash.starts_with(&r.docid));
    assert_eq!(r.body, "# Hello World\n\nhello world\n");
    assert_eq!(r.body_length, r.body.len());
    assert_eq!(r.modified_at, "");
    assert!(r.context.is_none());
    assert!(r.score > 0.0 && r.score < 1.0);
    assert_eq!(r.source, SearchSource::Fts);
}

#[test]
fn search_lex_prefix_vs_phrase() {
    let tmp = tempfile::tempdir().unwrap();
    let docs = tmp.path().join("docs");
    // "perform" is a prefix of "performance" and "performs"; a compound
    // term like "DEC-0054" requires adjacent tokens.
    write(&docs, "a.md", "# A\n\nperforms well\n");
    write(
        &docs,
        "b.md",
        "# B\n\nDEC and 0054 are separate words here\n",
    );
    let qmd = open_with_docs(&docs, &tmp.path().join("i.sqlite"));
    qmd.update(&qmd::UpdateOptions::default(), &mut |_| {})
        .unwrap();

    assert_eq!(lex(&qmd, "perform", 20).len(), 1);
    // "DEC-0054" is a phrase: "dec and 0054" is not an adjacent match.
    assert!(lex(&qmd, "DEC-0054", 20).is_empty());
}

#[test]
fn search_lex_cjk_query() {
    let tmp = tempfile::tempdir().unwrap();
    let docs = tmp.path().join("docs");
    write(&docs, "cjk.md", "# 数据库优化\n\n查询性能调优\n");
    write(&docs, "latin.md", "# Plain\n\nunrelated text\n");
    let qmd = open_with_docs(&docs, &tmp.path().join("i.sqlite"));
    qmd.update(&qmd::UpdateOptions::default(), &mut |_| {})
        .unwrap();

    let hits = lex(&qmd, "数据库", 20);
    assert_eq!(hits.len(), 1);
    assert_eq!(hits[0].display_path, "docs/cjk.md");
}

#[test]
fn search_lex_collection_scope_and_merge() {
    let tmp = tempfile::tempdir().unwrap();
    let a = tmp.path().join("a");
    let b = tmp.path().join("b");
    write(&a, "a.md", "# A\n\nhello world greeting\n");
    write(&b, "b.md", "# B\n\nhello there\n");
    let db = tmp.path().join("i.sqlite");
    let qmd = Qmd::builder(&db)
        .environment(Environment::default())
        .build()
        .unwrap();
    for (name, dir) in [("ca", &a), ("cb", &b)] {
        qmd.add_collection(
            name,
            &CollectionSpec {
                path: dir.to_string_lossy().into_owned(),
                ..CollectionSpec::default()
            },
        )
        .unwrap();
    }
    qmd.update(&qmd::UpdateOptions::default(), &mut |_| {})
        .unwrap();

    // Single-collection scope restricts results.
    let scoped = qmd
        .search_lex(
            "hello",
            &LexOptions {
                limit: Some(20),
                collections: Some(vec!["ca".to_owned()]),
            },
        )
        .unwrap();
    assert_eq!(scoped.len(), 1);
    assert_eq!(scoped[0].collection_name, "ca");

    // Multi-collection merges both lists by score.
    let merged = qmd
        .search_lex(
            "hello",
            &LexOptions {
                limit: Some(20),
                collections: Some(vec!["ca".to_owned(), "cb".to_owned()]),
            },
        )
        .unwrap();
    assert_eq!(merged.len(), 2);

    // Unknown collection names yield nothing.
    let none = qmd
        .search_lex(
            "hello",
            &LexOptions {
                limit: Some(20),
                collections: Some(vec!["nosuch".to_owned()]),
            },
        )
        .unwrap();
    assert!(none.is_empty());
}

#[test]
fn search_lex_context_included() {
    let tmp = tempfile::tempdir().unwrap();
    let docs = tmp.path().join("docs");
    write(&docs, "sub/a.md", "# A\n\nhello world\n");
    let db = tmp.path().join("i.sqlite");
    let qmd = open_with_docs(&docs, &db);
    qmd.update(&qmd::UpdateOptions::default(), &mut |_| {})
        .unwrap();

    qmd.add_context("docs", "/", "docs collection context")
        .unwrap();
    qmd.add_context("docs", "sub", "sub dir context").unwrap();
    qmd.set_global_context(Some("global context")).unwrap();

    let [r] = lex(&qmd, "hello", 20).try_into().unwrap();
    assert_eq!(
        r.context.as_deref().unwrap(),
        "global context\n\ndocs collection context\n\nsub dir context"
    );
}

#[test]
fn search_lex_empty_for_invalid_or_absent() {
    let tmp = tempfile::tempdir().unwrap();
    let docs = tmp.path().join("docs");
    write(&docs, "a.md", "# A\n\nhello\n");
    let qmd = open_with_docs(&docs, &tmp.path().join("i.sqlite"));
    qmd.update(&qmd::UpdateOptions::default(), &mut |_| {})
        .unwrap();

    assert!(lex(&qmd, "", 20).is_empty());
    assert!(lex(&qmd, "!!!", 20).is_empty());
    assert!(lex(&qmd, "-hello", 20).is_empty());
    assert!(lex(&qmd, "nosuchterm", 20).is_empty());
}

// --- extractSnippet ---------------------------------------------------------

#[test]
fn extract_snippet_best_line_window() {
    // JS `split('\n')`: the trailing newline leaves an empty 6th line,
    // which counts toward linesAfter.
    let body = "line one\nline two has alpha and beta\nline three\nline four\nline five\n";
    let r = qmd::extract_snippet(body, "alpha beta", 500);
    assert_eq!(r.line, 2);
    assert_eq!(r.snippet_lines, 4);
    assert_eq!(r.lines_before, 0);
    assert_eq!(r.lines_after, 2);
    assert_eq!(
        r.snippet,
        "@@ -1,4 @@ (0 before, 2 after)\nline one\nline two has alpha and beta\nline three\nline four"
    );
}

#[test]
fn extract_snippet_truncates_long_text() {
    let body = "x ".repeat(400); // 800 chars on one line
    let r = qmd::extract_snippet(&body, "x", 100);
    assert!(r.snippet.ends_with("..."));
}

#[test]
fn extract_snippet_counts_trailing_empty_line() {
    // JS `split('\n')` semantics: "a\n" has 2 lines, and the window
    // [best-1, best+3) includes the trailing empty one.
    let r = qmd::extract_snippet("a\n", "a", 500);
    assert_eq!(r.snippet_lines, 2);
    assert_eq!(r.lines_after, 0);
    assert_eq!(r.snippet, "@@ -1,2 @@ (0 before, 0 after)\na\n");
}

#[test]
fn add_line_numbers_starts_at_given_line() {
    assert_eq!(qmd::add_line_numbers("a\nb", 1), "1: a\n2: b");
    assert_eq!(qmd::add_line_numbers("a", 40), "40: a");
}
