//! Golden tests for virtual paths, docids and line suffixes (P1.4):
//! `vpath::{normalize, is_virtual, parse, build, parse_line_suffix}` and
//! `docid::{normalize, is_docid, get_docid}` against
//! `fixtures/vpath_golden.json`, generated by `scripts/gen_vpath_golden.ts`
//! running upstream v2.8.3 (`store.ts:698-801, 3401-3487`,
//! `qmd.ts:1261-1282`).

#![allow(
    unused_crate_dependencies,
    reason = "each test binary only uses a subset of the package deps"
)]
#![allow(
    clippy::tests_outside_test_module,
    clippy::doc_markdown,
    clippy::indexing_slicing,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    reason = "idiomatic test-code patterns"
)]

use qmd::docid::{is_docid, normalize_docid};
use qmd::vpath::{is_virtual_path, normalize_virtual_path, parse_line_suffix, parse_virtual_path};
use qmd::{build_virtual_path, get_docid};
use serde_json::Value;

fn fixture() -> Value {
    serde_json::from_str(include_str!("fixtures/vpath_golden.json")).unwrap()
}

#[test]
fn normalize_golden() {
    for case in fixture()["normalize"].as_array().unwrap() {
        let input = case[0].as_str().unwrap();
        let expected = case[1].as_str().unwrap();
        assert_eq!(
            normalize_virtual_path(input),
            expected,
            "normalize({input:?})"
        );
    }
}

#[test]
fn is_virtual_golden() {
    for case in fixture()["is_virtual"].as_array().unwrap() {
        let input = case[0].as_str().unwrap();
        let expected = case[1].as_bool().unwrap();
        assert_eq!(is_virtual_path(input), expected, "is_virtual({input:?})");
    }
}

#[test]
fn parse_golden() {
    for case in fixture()["parse"].as_array().unwrap() {
        let input = case[0].as_str().unwrap();
        match (&case[1], parse_virtual_path(input)) {
            (Value::Null, None) => {}
            (Value::Object(o), Some(vp)) => {
                assert_eq!(
                    vp.collection_name,
                    o["collectionName"].as_str().unwrap(),
                    "collection of {input:?}"
                );
                assert_eq!(vp.path, o["path"].as_str().unwrap(), "path of {input:?}");
                let expected_index = o.get("indexName").and_then(Value::as_str);
                assert_eq!(
                    vp.index_name.as_deref(),
                    expected_index,
                    "index of {input:?}"
                );
            }
            (expected, got) => panic!("parse({input:?}) = {got:?}, expected {expected}"),
        }
    }
}

#[test]
fn build_golden() {
    for case in fixture()["build"].as_array().unwrap() {
        let args = case[0].as_array().unwrap();
        let collection = args[0].as_str().unwrap();
        let path = args[1].as_str().unwrap();
        let index = args[2].as_str();
        let expected = case[1].as_str().unwrap();
        assert_eq!(
            build_virtual_path(collection, path, index),
            expected,
            "build({collection:?}, {path:?}, {index:?})"
        );
    }
}

#[test]
fn docid_golden() {
    for case in fixture()["docid"].as_array().unwrap() {
        let input = case[0].as_str().unwrap();
        let expected = &case[1];
        assert_eq!(
            normalize_docid(input),
            expected["normalized"].as_str().unwrap(),
            "normalize_docid({input:?})"
        );
        assert_eq!(
            is_docid(input),
            expected["is_docid"].as_bool().unwrap(),
            "is_docid({input:?})"
        );
    }
}

#[test]
fn get_docid_golden() {
    for case in fixture()["get_docid"].as_array().unwrap() {
        let input = case[0].as_str().unwrap();
        let expected = case[1].as_str().unwrap();
        assert_eq!(get_docid(input), expected, "get_docid({input:?})");
    }
}

#[test]
fn line_suffix_golden() {
    for case in fixture()["line_suffix"].as_array().unwrap() {
        let input = case[0].as_str().unwrap();
        let expected = &case[1];
        let got = parse_line_suffix(input);
        assert_eq!(
            got.path,
            expected["path"].as_str().unwrap(),
            "path of {input:?}"
        );
        assert_eq!(
            got.from_line,
            expected["from_line"].as_u64(),
            "from_line of {input:?}"
        );
        assert_eq!(
            got.max_lines,
            expected["max_lines"].as_u64(),
            "max_lines of {input:?}"
        );
    }
}
